Traceback (most recent call last):
  File "/protein_prep/protein_prep.py", line 48, in <module>
    main()
  File "/protein_prep/protein_prep.py", line 40, in main
    min_pdb, rmsd = run_pipeline()
  File "/protein_prep/protein_prep.py", line 8, in run_pipeline
    param = parse_arguments()
  File "/protein_prep/utils/init.py", line 9, in parse_arguments
    template_pdb = config["protein_prep"]["template_pdb"]
  File "/root/miniconda3/envs/protein_prep/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'protein_prep'
